### ISSUE TITLE
[Backend] Scraping Job Architecture

### ISSUE THREAD

**Issue by olivierobert** [trathailoi/gsrc-exercise#18]
## Issue

In the current implementation, the keyword entity contains an attribute named `jobQueueId` which is a reference to the job ID managed in the Redis-backed and Bull-backed jobs handler. However, the current architecture entails that the jobs are created in the database before the keywords:

https://github.com/trathailoi/gsrc-exercise/blob/08bb6434d92faa8bba3ab7e4122ac651d843a76e/backend/src/keyword/keyword.service.ts#L35-L36

https://github.com/trathailoi/gsrc-exercise/blob/08bb6434d92faa8bba3ab7e4122ac651d843a76e/backend/src/keyword/keyword.service.ts#L54-L62

This causes a very tight coupling between the keyword and the job handling. Say if there were several jobs (to do various kinds of processing) for a keyword then this implementation would make it harder.

## Expected

The job entity stores a reference to the keyword (or any other entity it needs to deal with) and then fetches the keyword information when performing the job. Upon completion, it is standard to update the fetched entity with the required data.

**Comment by trathailoi** [comment]
I was thinking of the "search again" feature on users' end. That leads me to having the `jobQueueId` attribute stored in the `keyword` entity, so that we can refer to the latest scraping job of a keyword. On a second thought, with your suggestion, we can also get the latest job by sorting by created time in the jobs queue. So, your suggestion is better, I will address this.

**Comment by trathailoi** [comment]
Hi @olivierobert , 

To avoid conflicts, I have to merge the PRs myself, and it automatically close the issues. Would you mind re-opening the issue if there is any thing missing. Thank you in advance.
