### ISSUE TITLE
[Question] Why using Naive UI and Tailwind at the same time?

### ISSUE THREAD

**Issue by olivierobert** [trathailoi/gsrc-exercise#21]
## Issue

Both Naive UI and Tailwind are defined as dependencies for the project:

https://github.com/trathailoi/gsrc-exercise/blob/08bb6434d92faa8bba3ab7e4122ac651d843a76e/package.json#L21

https://github.com/trathailoi/gsrc-exercise/blob/08bb6434d92faa8bba3ab7e4122ac651d843a76e/package.json#L75

What is the reason for doing so? Also, that begs the question of if all the dependencies defined are in use e.g., `vuedraggable`, `vis-timeline`, etc.

## Expected

Only the required and in-use dependencies should be defined in the project.

**Comment by trathailoi** [comment]
My bad. Those two `vuedraggable` and `vis-timeline` are redundant to this challenge. I will get rid of them now.

Regarding Naive UI and Tailwind, as far as I see, Naive UI is a component library whereas Tailwind is a CSS framework. From my point of view, they are different things serving different needs. I just love them both because they are convenient to use and highly customizable, and also because of their major advantages:
- Naive UI for its beautiful & handy pre-made components, come along with well-documented docs.
- Tailwind for its flexible utility classes and minimal bundle size with PurgeCSS.

[Naive UI](https://www.naiveui.com/en-US/dark/components/grid) and [Tailwind](https://tailwindcss.com/docs/grid-template-columns) may overlap at responsiveness capabilities, but it is not necessarily a conflict, as a team, we can discuss about the pros and cons of them and make agreement on this.

That's just my opinion anyway, I would love to hear yours.

**Comment by olivierobert** [comment]
Since Tailwind seems to be mostly used for layout things, it might be simple to DYI it 😅  In addition to utility class names, Tailwind comes with themability and overrides for all built-in HTML elements (e.g., <button/>, <a/>`). Since the latter is taken care of by Native UI, it removes a lot of the benefits from Tailwind. Also, with things like `grid` and `min()` / `max()` / `clamp()` in CSS make it much easier to build responsive layouts compared to a few years ago.
